### ISSUE TITLE
API to generate diagram images

### ISSUE THREAD

**Issue by garriguv** [rngtng/vizard#9]
Some kind of api that we could curl to generate images of diagrams, something we could use in our CI to automatically generate new diagrams if a file changed.
Would be pretty neat :)

**Comment by rngtng** [comment]
there is actually one, but not documented :)

Just call `POST http://vizard.io/render.png` and pass the UML as body

**Comment by garriguv** [comment]
:+1: thanks!

**Comment by phoet** [comment]
i used a file to store the uml:

```ruby
namespace :doc do
  desc "generate the diagram"
  task :uml do
    content = File.read('flow.uml')
    cmd = "curl 'http://vizard.io/render.png' -sS -o diagram.png --data $'\n#{content}\n\n'"
    `#{cmd}`
  end
end
```
